/* Single selector table. Keep browser DOM changes here. No prompt content is exported. */
(function(root){
 const sites={
  claude:{host:'claude.ai',user:'[data-testid="user-message"], .font-user-message',composer:'[contenteditable="true"].ProseMirror, [data-testid="chat-input"]',send:'button[aria-label="Send message"], button[aria-label="Send Message"]',mock:{user:'<div data-testid="user-message"></div>',composer:'<div class="ProseMirror" contenteditable="true"></div>',send:'<button aria-label="Send message">Send</button>'}},
  chatgpt:{host:'chatgpt.com',user:'[data-message-author-role="user"]',composer:'#prompt-textarea',send:'button[data-testid="send-button"]',mock:{user:'<div data-message-author-role="user"></div>',composer:'<div id="prompt-textarea" contenteditable="true"></div>',send:'<button data-testid="send-button">Send</button>'}},
  gemini:{host:'gemini.google.com',user:'user-query, .user-query-container',composer:'rich-textarea [contenteditable="true"], textarea[aria-label="Enter a prompt here"]',send:'button.send-button, button[aria-label="Send message"]',mock:{user:'<user-query></user-query>',composer:'<rich-textarea><div contenteditable="true"></div></rich-textarea>',send:'<button class="send-button">Send</button>'}},
  perplexity:{host:'www.perplexity.ai',aliases:['perplexity.ai'],user:'[data-testid="user-message"], [data-testid="query"]',composer:'textarea[placeholder], [contenteditable="true"][role="textbox"]',send:'button[aria-label="Submit"], button[aria-label="Send"]',mock:{user:'<div data-testid="query"></div>',composer:'<textarea placeholder="Ask anything"></textarea>',send:'<button aria-label="Submit">Send</button>'}},
  copilot:{host:'copilot.microsoft.com',user:'[data-content="user-message"], [data-testid="user-message"]',composer:'textarea#userInput, textarea[placeholder], [contenteditable="true"][role="textbox"]',send:'button[aria-label="Submit message"], button[title="Submit message"]',mock:{user:'<div data-content="user-message"></div>',composer:'<textarea id="userInput" placeholder="Message Copilot"></textarea>',send:'<button aria-label="Submit message">Send</button>'}},
  grok:{host:'grok.com',user:'[data-testid="user-message"], [data-role="user"]',composer:'textarea, [contenteditable="true"][role="textbox"]',send:'button[aria-label="Send"], button[type="submit"]',mock:{user:'<div data-role="user"></div>',composer:'<textarea></textarea>',send:'<button aria-label="Send">Send</button>'}},
  deepseek:{host:'chat.deepseek.com',user:'[data-testid="user-message"], .ds-message--user, [data-role="user"]',composer:'textarea#chat-input, textarea[placeholder]',send:'button[aria-label="Send"], [role="button"][aria-label="Send"]',mock:{user:'<div class="ds-message--user"></div>',composer:'<textarea id="chat-input" placeholder="Message DeepSeek"></textarea>',send:'<button aria-label="Send">Send</button>'}},
  mistral:{host:'chat.mistral.ai',user:'[data-message-author-role="user"], [data-testid="user-message"]',composer:'textarea, [contenteditable="true"].ProseMirror',send:'button[aria-label="Send message"], button[type="submit"]',mock:{user:'<div data-message-author-role="user"></div>',composer:'<textarea></textarea>',send:'<button aria-label="Send message">Send</button>'}},
  aistudio:{host:'aistudio.google.com',user:'ms-chat-turn[data-role="user"], [data-turn-role="user"]',composer:'textarea[aria-label="Type something"], ms-prompt-input-wrapper textarea',send:'button[aria-label="Run"], button[aria-label="Run prompt"]',mock:{user:'<ms-chat-turn data-role="user"></ms-chat-turn>',composer:'<ms-prompt-input-wrapper><textarea aria-label="Type something"></textarea></ms-prompt-input-wrapper>',send:'<button aria-label="Run">Run</button>'}}
 };
 root.THIRSTY_SITES=sites;if(typeof module!=='undefined')module.exports=sites;
})(typeof globalThis!=='undefined'?globalThis:this);
