'use strict';
/* Full acceptance runner. All writes stay in this checkout, all source logs read-only. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),os=require('node:os');
const {execFileSync}=require('node:child_process');const {chromium}=require('playwright');const {root,temp,sleep,until,launch}=require('./helpers');
const {Store,atomic}=require('../engine/store');const runBackfill=require('./real-backfill');const sites=require('../../extension/sites');
const resultsFile=path.join(__dirname,'acceptance-results.json');let results={};try{results=JSON.parse(fs.readFileSync(resultsFile));}catch{}
function record(item,value){results[item]={passed:true,...value};fs.writeFileSync(resultsFile,JSON.stringify(results,null,2));console.log('PASS '+item+' '+JSON.stringify(value));}
async function live(){const claudeDir=temp('live-claude'),codexDir=temp('live-codex'),dataDir=temp('live-data');const c=path.join(claudeDir,'test.jsonl'),x=path.join(codexDir,'rollout-test.jsonl');fs.writeFileSync(c,'');fs.writeFileSync(x,'');const run=await launch({claudeDir,codexDir,dataDir});
 try{const before=await run.stats(),ts=new Date().toISOString(),started=performance.now();const reply=i=>({type:'assistant',timestamp:ts,message:{id:'acceptance-one-reply',content:[{type:'text',text:'x'}],usage:{input_tokens:20,output_tokens:10+i}}});fs.appendFileSync(c,[0,1,2].map(i=>JSON.stringify(reply(i))).join('\n')+'\n');fs.appendFileSync(x,JSON.stringify({type:'event_msg',timestamp:ts,payload:{type:'token_count',info:{total_token_usage:{input_tokens:100,output_tokens:20,total_tokens:120},last_token_usage:{input_tokens:100,output_tokens:20,total_tokens:120}}}})+'\n');const after=await until(async()=>{const s=await run.stats();return s.today.sips===before.today.sips+2?s:null;},3000);const latencyMs=performance.now()-started;
 const body=JSON.stringify({source:'web',site:'chatgpt',kind:'prompt',id:'accepted-once',ts});const accepted=await fetch(run.url+'/event',{method:'POST',headers:{Origin:'chrome-extension://abc','Content-Type':'application/json'},body});assert.equal(accepted.status,200);assert.equal((await accepted.json()).deduped,false);const duplicate=await fetch(run.url+'/event',{method:'POST',headers:{Origin:'chrome-extension://abc','Content-Type':'application/json'},body});assert.equal((await duplicate.json()).deduped,true);assert.equal((await fetch(run.url+'/event',{method:'POST',headers:{'Content-Type':'application/json'},body})).status,403);const final=await run.stats();assert.equal(final.today.sips,3);assert.equal(final.today.prompts,1);
 const window=await run.app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.getBounds().width===240);return {focusable:w.isFocusable(),alwaysOnTop:w.isAlwaysOnTop(),skipTaskbar:typeof w.isSkipTaskbar==="function"?w.isSkipTaskbar():null};});assert.equal(window.focusable,false);assert.equal(window.alwaysOnTop,true);
 record(3,{beforeSips:before.today.sips,afterLogSips:after.today.sips,finalSips:final.today.sips,latencyMs,accepted:200,duplicate:true,withoutOrigin:403,window});return {dataDir,claudeDir,codexDir};
 }finally{await run.close();}
}
async function real(evidence){const run=await launch({dataDir:evidence.dataDir,claudeDir:evidence.claudeDir,codexDir:evidence.codexDir});fs.writeFileSync(path.join(root,'.testdata/real-live.json'),JSON.stringify({dataDir:run.dataDir,url:run.url,pid:run.app.process().pid,started:Date.now()}));
 try{const before=(await run.stats()).bySource.codex.sips,started=Date.now();console.log('REAL E2E BEFORE '+before+' '+new Date().toISOString());
  // During this wait the active Codex session continues implementing and reviewing.
  await sleep(120000);const after=(await run.stats()).bySource.codex.sips;assert.ok(after>before,`Codex sips did not rise: ${before} -> ${after}`);record(4,{before,after,elapsedMs:Date.now()-started});
  await idleCheck(run);
  fs.writeFileSync(path.join(__dirname,'real-stats.json'),JSON.stringify(await run.stats(),null,2));
 }finally{await run.close();}
}
// Item 6 on its own (--phase=idle), so it can run when no Codex session is producing replies for item 4.
// Memory is the sum of private bytes; working sets count pages shared between Electron processes.
async function idleCheck(run){console.log('IDLE WINDOW START '+new Date().toISOString());const samples=[];for(let i=0;i<6;i++){await sleep(10000);samples.push(await run.app.evaluate(({app})=>app.getAppMetrics()));}const last=samples.at(-1);const cpuPercent=samples.reduce((sum,s)=>sum+s.reduce((n,p)=>n+p.cpu.percentCPUUsage,0),0)/samples.length;const memoryMB=last.reduce((sum,p)=>sum+(p.memory.privateBytes??p.memory.workingSetSize),0)/1024;const info={idleSeconds:60,cpuPercent,memoryMB,processes:last.map(p=>({pid:p.pid,type:p.type,cpuPercent:p.cpu.percentCPUUsage,memoryMB:(p.memory.privateBytes??p.memory.workingSetSize)/1024}))};record(6,{...info,cpuTargetMet:cpuPercent<1,memoryTargetMet:memoryMB<500});assert.ok(cpuPercent<1,'Idle CPU exceeds 1 percent: '+cpuPercent);assert.ok(memoryMB<500,'Total app memory exceeds 500 MB: '+memoryMB);}
async function idle(evidence){const run=await launch({dataDir:evidence.dataDir,claudeDir:evidence.claudeDir,codexDir:evidence.codexDir});try{await idleCheck(run);}finally{await run.close();}}
async function capture(pass=1){const evidence=JSON.parse(fs.readFileSync(path.join(__dirname,'backfill-results.json')));const saved=JSON.parse(fs.readFileSync(path.join(evidence.dataDir,'stats.json')));const dataDir=temp('shots'),claudeDir=temp('shots-c'),codexDir=temp('shots-x');atomic(path.join(dataDir,'stats.json'),saved);atomic(path.join(dataDir,'settings.json'),JSON.parse(fs.readFileSync(path.join(evidence.dataDir,'settings.json'))));const shotDir=path.join(root,'shots','pass'+pass);fs.mkdirSync(shotDir,{recursive:true});const paths=[];
 for(const scale of [1,1.25,1.5]){const run=await launch({dataDir,claudeDir,codexDir,scale});try{const page=await run.app.firstWindow();await page.waitForFunction(()=>!!window.thirstyPreview);await page.evaluate(()=>document.fonts.ready);const stats=await run.stats();for(const [name,ratio]of Object.entries({chill:.1,sipping:.5,sweating:.85,bloated:1.4,dramatic:2.4,sleeping:.2,gulp:.5})){
   const png=path.join(shotDir,`${name}-${Math.round(scale*100)}-alpha.png`);await page.evaluate(({stats,name,ratio})=>{document.getElementById('bubble').classList.remove('show');document.getElementById('pop').classList.remove('show');const s=structuredClone(stats);s.today.litres=s.ration*ratio;s.today.sips=Math.round(s.today.litres/.0035);s.mood=name==='gulp'?'sipping':name;s.lastSip=name==='sleeping'?Date.now()-1801000:Date.now();window.thirstyPreview.draw(s);if(name==='gulp')window.thirstyPreview.gulp(5,'codex');},{stats,name,ratio});if(name==='gulp')await page.waitForTimeout(190);else await page.waitForTimeout(80);
   await run.app.evaluate(async({BrowserWindow},png)=>{const w=BrowserWindow.getAllWindows().find(w=>w.isAlwaysOnTop());const image=await w.webContents.capturePage();process.mainModule.require('node:fs').writeFileSync(png,image.toPNG());},png);paths.push(png);
  }
  // Loading replacement, all pet sizes, and strict visible-box overlap check.
  for(const size of ['S','M','L']){await page.evaluate(size=>window.thirsty.settings({size}),size);await page.waitForTimeout(60);await page.evaluate(()=>{document.body.classList.add('tracking-loading');const p=document.getElementById('loading');p.classList.remove('hidden');p.textContent='WAKING UP... 330 / 595';});const overlap=await page.evaluate(()=>{const r=document.getElementById('ration'),p=document.getElementById('loading');return {rationHidden:getComputedStyle(r).visibility==='hidden',progressBottom:p.getBoundingClientRect().bottom,viewport:innerHeight};});assert.equal(overlap.rationHidden,true);assert.ok(overlap.progressBottom<=overlap.viewport+1);const png=path.join(shotDir,`loading-${size}-${Math.round(scale*100)}-alpha.png`);await run.app.evaluate(async({BrowserWindow},png)=>{const image=await BrowserWindow.getAllWindows().find(w=>w.isAlwaysOnTop()).webContents.capturePage();process.mainModule.require('node:fs').writeFileSync(png,image.toPNG());},png);paths.push(png);}
  if(scale===1){await run.app.evaluate(()=>process.mainModule.require(process.mainModule.require('node:path').resolve(process.cwd(),'main.js')).openDashboard());const dashboard=await until(async()=>{for(const p of run.app.windows())if(p.url().includes('dashboard.html'))return p;});await dashboard.waitForFunction(()=>!!window.thirstyDashboard);await dashboard.evaluate(s=>window.thirstyDashboard.render(s),stats);await dashboard.evaluate(()=>document.fonts.ready);await dashboard.waitForTimeout(100);const png=path.join(shotDir,'dashboard-960x680.png');await run.app.evaluate(async({BrowserWindow},png)=>{const w=BrowserWindow.getAllWindows().find(w=>w.getTitle().includes('cooling loop'));w.setContentSize(960,680);await new Promise(r=>setTimeout(r,100));const im=await w.webContents.capturePage();process.mainModule.require('node:fs').writeFileSync(png,im.toPNG());},png);paths.push(png);const card=await dashboard.evaluate(()=>window.thirstyDashboard.share());assert.ok(fs.existsSync(card));paths.push(card);}
 }finally{await run.close();}}
 const combined=JSON.parse(execFileSync('python',[path.join(__dirname,'compose-shots.py'),shotDir],{encoding:'utf8'}));record(5,{...(results[5]||{}),capturePass:pass,captures:paths,composites:combined,realSeries:true,scales:[100,125,150],sizes:['S','M','L'],reviewPasses:results[5]?.reviewPasses||0});return paths;
}
function mockHTML(s){return `<!doctype html><html><head><meta charset="utf-8"></head><body><main id="conversation"></main><form>${s.mock.composer}${s.mock.send}</form><script>const selectors=${JSON.stringify(s)},chat=document.getElementById('conversation');function message(text){const t=document.createElement('template');t.innerHTML=selectors.mock.user;const n=t.content.firstElementChild;n.textContent=text;chat.append(n);}for(let i=0;i<5;i++)message('history '+i);const c=document.querySelector(selectors.composer),send=document.querySelector(selectors.send);function submit(){const text=c.value??c.textContent;if(!text.trim())return;message(text);if('value' in c)c.value='';else c.textContent='';setTimeout(()=>{const r=document.createElement('div');r.className='mock-answer';chat.append(r);let k=0;const t=setInterval(()=>{r.textContent+='A mock answer streams in. ';if(++k===8)clearInterval(t);},100);},300);}c.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}});send.addEventListener('click',e=>{e.preventDefault();submit();});document.querySelector('form').addEventListener('submit',e=>e.preventDefault());</script></body></html>`;}
async function extension(){const claudeDir=temp('ext-c'),codexDir=temp('ext-x'),dataDir=temp('ext-data');let run=await launch({claudeDir,codexDir,dataDir});
 // The extension probes 47821 to 47841, so a real pet on 47821 would receive the test prompts.
 if(run.port!==47821){await run.close();throw new Error('A THIRSTY pet is already running on port 47821. Quit it (tray, Quit) before the extension phase, or it receives the test prompts.');}
const extPath=path.resolve(root,'../extension');const profile=temp('chromium-profile');const context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extPath}`,`--load-extension=${extPath}`,'--disable-features=MediaRouter'],env:{...process.env},viewport:{width:960,height:680}});let mock;
 try{const sw=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');await sw.evaluate(port=>chrome.storage.local.set({port}),run.port);const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));await context.route('https://**/*',route=>{const host=new URL(route.request().url()).hostname;const s=Object.values(sites).find(s=>[s.host,...s.aliases||[]].includes(host));if(s)route.fulfill({status:200,contentType:'text/html',body:mockHTML(s)});else route.abort();});const checked=[];
  for(const [site,s]of Object.entries(sites)){const page=await context.newPage();await page.goto('https://'+s.host+'/thirsty-test');await page.waitForTimeout(2200);const history=(await run.stats()).bySource['web:'+site];assert.equal(history.sips,0);assert.equal(history.prompts,0);
   for(let i=0;i<3;i++){const c=page.locator(s.composer).first();await c.fill('prompt '+site+' '+i);if(i===1)await page.locator(s.send).first().click();else await c.press('Enter');await page.waitForTimeout(250);}await until(async()=>{const v=(await run.stats()).bySource['web:'+site];return v.sips===3&&v.prompts===3;},10000);checked.push({site,historySips:0,prompts:3,sips:3,enter:2,sendButton:1});await page.close();}
  const page=await context.newPage(),s=sites.chatgpt;await page.goto('https://chatgpt.com/thirsty-offline');await page.waitForTimeout(2200);await run.close();run=null;for(let i=0;i<2;i++){const c=page.locator(s.composer).first();await c.fill('offline '+i);await c.press('Enter');await page.waitForTimeout(300);}await until(async()=>{const q=await sw.evaluate(()=>chrome.storage.local.get('queue'));return q.queue?.length===2;},15000);run=await launch({claudeDir,codexDir,dataDir});await until(async()=>{const v=(await run.stats()).bySource['web:chatgpt'];return v.prompts===5&&v.sips===5;},15000);assert.equal((await sw.evaluate(()=>chrome.storage.local.get('queue'))).queue.length,0);
  mock=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end('<!doctype html><title>THIRSTY bridge mock</title><p>Local bridge</p>');});await new Promise(resolve=>mock.listen(0,'127.0.0.1',resolve));const bridge=await context.newPage();await bridge.goto('http://127.0.0.1:'+mock.address().port);const bridged=await bridge.evaluate(()=>new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Bridge timeout')),12000);window.addEventListener('message',e=>{if(e.data?.type==='thirsty:stats'){clearTimeout(timeout);resolve(e.data.stats);}});window.postMessage({type:'thirsty:hello'},location.origin);}));assert.equal(bridged.today.sips,29);assert.equal(bridged.today.prompts,29);const direct=await run.stats();assert.equal(bridged.today.sips,direct.today.sips);assert.deepEqual(errors,[]);record(7,{sites:checked,offlineQueued:2,offlineFlushed:2,queueRemaining:0,bridge:{sips:bridged.today.sips,prompts:bridged.today.prompts},browserErrors:errors});
 }finally{await context.close();if(run)await run.close();if(mock)await new Promise(r=>mock.close(r));}
}
function punctuation(){const checked=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.testdata','.npm-cache','fonts','img','shots','icons'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(/\.(html|css|js|md)$/.test(e.name)){const t=fs.readFileSync(p,'utf8');assert.ok(!/[\u2013\u2014\u00b7]/.test(t),'Forbidden punctuation: '+p);checked.push(path.relative(path.join(root,'..'),p));}}}walk(path.join(root,'renderer'));walk(path.join(root,'../extension'));checked.push('widget/README.md');assert.ok(!/[\u2013\u2014\u00b7]/.test(fs.readFileSync(path.join(root,'README.md'),'utf8')));record(8,{files:checked.length,forbiddenCharacters:0});}
async function main(){const phase=process.argv.find(a=>a.startsWith('--phase='))?.split('=')[1];if(phase==='live')return live();if(phase==='extension')return extension();if(phase==='shots')return capture(Number(process.argv.find(a=>a.startsWith('--pass='))?.split('=')[1]||1));if(phase==='punctuation')return punctuation();if(phase==='idle')return idle(JSON.parse(fs.readFileSync(path.join(__dirname,'backfill-results.json'))));if(phase==='real'){const evidence=JSON.parse(fs.readFileSync(path.join(__dirname,'backfill-results.json')));return real(evidence);}
 const unit=execFileSync(process.execPath,['--test',path.join(__dirname,'engine.test.js')],{encoding:'utf8'});fs.writeFileSync(path.join(__dirname,'unit-output.txt'),unit);record(1,{output:unit});const evidence=await runBackfill();record(2,evidence);await live();await extension();await capture(1);await real(evidence);punctuation();console.log('Acceptance runner finished. Visual review and second capture are recorded separately.');}
main().catch(e=>{console.error(e.stack);results.failure={message:e.message,stack:e.stack};fs.writeFileSync(resultsFile,JSON.stringify(results,null,2));process.exitCode=1;});
