'use strict';
const {app,BrowserWindow,Tray,Menu,ipcMain,screen,nativeImage,clipboard,ClipboardItem,shell,dialog}=require('electron');
const path=require('node:path'),fs=require('node:fs'),os=require('node:os');
const {Collectors}=require('./engine/collectors');const {Store,load,day,atomic}=require('./engine/store');const {startAPI}=require('./engine/api');
const dataDir=path.resolve(process.env.THIRSTY_DATA_DIR || path.join(process.platform==='darwin'?path.join(os.homedir(),'Library/Application Support'):process.env.APPDATA||path.join(os.homedir(),'.config'),'Thirsty'));
fs.mkdirSync(dataDir,{recursive:true});app.setPath('userData',dataDir);app.setPath('sessionData',path.join(dataDir,'chromium'));app.setPath('logs',path.join(dataDir,'logs'));
app.commandLine.appendSwitch('disk-cache-dir',path.join(dataDir,'cache'));
const testing=process.env.THIRSTY_TEST_MODE==='1',mac=process.platform==='darwin';
// One pet per data folder: a second launch (Start Menu, login item, installer) opens the dashboard instead.
const primary=testing||app.requestSingleInstanceLock();if(!primary)app.exit(0);app.on('second-instance',()=>openDashboard());
if(testing){app.commandLine.appendSwitch('no-sandbox');app.commandLine.appendSwitch('disable-gpu-sandbox');}let widget,dashboard,tray,collectors,api,store,progress,quitting=false,dragStart;
const initial=load(path.join(dataDir,'settings.json'),{});
const config={dataDir,claudeDir:process.env.THIRSTY_CLAUDE_DIR||initial.claudeDir||path.join(os.homedir(),'.claude/projects'),codexDir:process.env.THIRSTY_CODEX_DIR||initial.codexDir||path.join(os.homedir(),'.codex/sessions')};
function emit(name,data){for(const w of [widget,dashboard])if(w&&!w.isDestroyed())w.webContents.send(name,data);}
function currentSettings(){return store?.settings||{size:'M',sound:false,ghost:false,startAtLogin:true,positions:{},...initial};}
function bounds(reset=false){const settings=currentSettings(),size={S:180,M:240,L:320}[settings.size]||240;const height=Math.round(size*280/240),display=screen.getPrimaryDisplay(),a=display.workArea;const saved=!reset&&settings.positions?.[display.id];let x=saved?.x??a.x+a.width-size-16,y=saved?.y??a.y+a.height-height-16;
 const on=screen.getAllDisplays().find(d=>x>=d.workArea.x&&x+size<=d.workArea.x+d.workArea.width&&y>=d.workArea.y&&y+height<=d.workArea.y+d.workArea.height);if(!on){x=a.x+a.width-size-16;y=a.y+a.height-height-16;}return {width:size,height,x:Math.round(x),y:Math.round(y)};}
function applySettings(reset=false){if(!widget)return;widget.setBounds(bounds(reset));widget.setIgnoreMouseEvents(!!currentSettings().ghost,{forward:true});widget.setOpacity(currentSettings().ghost?.56:1);if(!testing)app.setLoginItemSettings(app.isPackaged?{openAtLogin:!!currentSettings().startAtLogin,name:'THIRSTY'}:{openAtLogin:!!currentSettings().startAtLogin,name:'THIRSTY',path:process.execPath,args:[path.resolve(__dirname)]});buildMenu();}
function savePosition(){if(!store || !widget)return;const b=widget.getBounds(),d=screen.getDisplayMatching(b),a=d.workArea;let x=Math.max(a.x+16,Math.min(a.x+a.width-b.width-16,b.x)),y=Math.max(a.y+16,Math.min(a.y+a.height-b.height-16,b.y));if(Math.abs(x-a.x-16)<24)x=a.x+16;if(Math.abs(a.x+a.width-b.width-16-x)<24)x=a.x+a.width-b.width-16;if(Math.abs(y-a.y-16)<24)y=a.y+16;if(Math.abs(a.y+a.height-b.height-16-y)<24)y=a.y+a.height-b.height-16;widget.setPosition(Math.round(x),Math.round(y));store.updateSettings({positions:{...store.settings.positions,[d.id]:{x,y}}});}
function openDashboard(){if(!app.isReady())return;if(dashboard&&!dashboard.isDestroyed()){dashboard.show();dashboard.focus();if(mac)app.focus({steal:true});return;}dashboard=new BrowserWindow({width:960,height:680,minWidth:760,minHeight:580,backgroundColor:'#1463FF',title:'THIRSTY, your cooling loop',autoHideMenuBar:true,show:false,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:!testing}});dashboard.loadFile(path.join(__dirname,'renderer/dashboard.html'));dashboard.once('ready-to-show',()=>{if(mac)app.dock?.show();dashboard.show();if(mac)app.focus({steal:true});});dashboard.on('closed',()=>{dashboard=null;if(mac)app.dock?.hide();});secure(dashboard);}
function secure(w){w.webContents.setWindowOpenHandler(({url})=>{if(/^https?:\/\//.test(url))shell.openExternal(url);return {action:'deny'};});w.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith('file:')){event.preventDefault();if(/^https?:\/\//.test(url))shell.openExternal(url);}});}
function buildMenu(){if(!tray)return;const s=currentSettings();const menu=Menu.buildFromTemplate([{label:'Open dashboard',click:openDashboard},{label:'Sound',type:'checkbox',checked:!!s.sound,click:i=>store?.updateSettings({sound:i.checked})},{label:'Size',submenu:['S','M','L'].map(size=>({label:size,type:'radio',checked:s.size===size,click:()=>{store?.updateSettings({size});applySettings();}}))},{label:'Ghost mode',type:'checkbox',checked:!!s.ghost,click:i=>{store?.updateSettings({ghost:i.checked});applySettings();}},{label:'Pause tracking for 1 hour',click:()=>store?.updateSettings({pausedUntil:Date.now()+3600000})},{label:'Resume tracking',enabled:Date.now()<(s.pausedUntil||0),click:()=>store?.updateSettings({pausedUntil:0})},{label:'Reset position',click:()=>{applySettings(true);savePosition();}},{label:'Start at login',type:'checkbox',checked:!!s.startAtLogin,click:i=>{store?.updateSettings({startAtLogin:i.checked});applySettings();}},{type:'separator'},{label:'Quit',click:()=>app.quit()}]);tray.setContextMenu(menu);return menu;}
function attachStore(next){store=next;store.on('change',s=>{emit('stats',s);buildMenu();});store.on('sip',e=>emit('sip',e));store.on('badge',e=>emit('badge',e));emit('stats',store.snapshot());applySettings();if(!store.settings.welcomed){emit('toast','Hi! I take a sip every time an AI answers you. Right-click me for settings.');store.updateSettings({welcomed:true,lastToastDay:day()});}else if(store.settings.lastToastDay!==day()){const s=store.snapshot(),y=s.yesterday;if(y.sips)emit('toast',`Yesterday: ${Math.round(y.ml)} mL across ${y.sips} sips. ${y.litres<=s.ration?'Under ration':'Over ration'}, streak ${s.streak}!`);store.updateSettings({lastToastDay:day()});}}
ipcMain.handle('stats',()=>store?.snapshot()||{loading:true,progress});
ipcMain.handle('settings',async(_,patch)=>{if(!store)throw new Error('Backfill in progress');const clean={};for(const key of ['ration','size','sound','ghost','startAtLogin','sources','claudeDir','codexDir','siteUrl'])if(key in patch)clean[key]=patch[key];if(clean.size&&!['S','M','L'].includes(clean.size))delete clean.size;const next=store.updateSettings(clean);applySettings();if(clean.claudeDir||clean.codexDir){await collectors.stop();Object.assign(config,{claudeDir:clean.claudeDir||config.claudeDir,codexDir:clean.codexDir||config.codexDir});await startCollectors();}return next;});
ipcMain.handle('poke',()=>store?.poke());ipcMain.on('dashboard',openDashboard);ipcMain.on('menu',()=>buildMenu()?.popup());
ipcMain.on('play',()=>{const url=currentSettings().siteUrl;if(/^https?:\/\//.test(url))shell.openExternal(url.replace(/#.*$/,'')+'#game');});
ipcMain.on('drag',(_,e)=>{if(!widget || currentSettings().ghost)return;if(!dragStart)dragStart=widget.getBounds();widget.setPosition(Math.round(dragStart.x+e.dx),Math.round(dragStart.y+e.dy));if(e.end){dragStart=null;savePosition();}});
ipcMain.handle('share',async(_,data)=>{if(typeof data!=='string'||!data.startsWith('data:image/png;base64,')||data.length>8e6)throw new Error('Invalid share card');const image=nativeImage.createFromDataURL(data);if(image.getSize().width!==1200||image.getSize().height!==675)throw new Error('Share card must be 1200 x 675');const directory=process.env.THIRSTY_PICTURES_DIR||app.getPath('pictures');fs.mkdirSync(directory,{recursive:true});const file=path.join(directory,`Thirsty-week-${day()}.png`);fs.writeFileSync(file,image.toPNG());await clipboard.write([new ClipboardItem({'image/png':new Blob([image.toPNG()],{type:'image/png'})})]);return file;});
ipcMain.handle('csv',async()=>{if(!store)return;const result=await dialog.showSaveDialog(dashboard,{defaultPath:path.join(testing?dataDir:app.getPath('documents'),'thirsty-daily.csv'),filters:[{name:'CSV',extensions:['csv']}]});if(!result.canceled){fs.writeFileSync(result.filePath,store.csv());return result.filePath;}});
async function startCollectors(){collectors=new Collectors(config);collectors.on('progress',p=>{progress=p;emit('progress',p);});collectors.on('error',e=>{console.error(e);emit('toast','Tracking error. Check the log folders in Settings.');});collectors.on('ready',(s,result)=>{attachStore(s);if(!s.settings.rationToastShown&&s.settings.usualDay){setTimeout(()=>{emit('toast',`Your usual day: ${s.settings.usualDay.toFixed(1)} L. Ration set to ${s.settings.ration} L. Beat it to start a streak.`);s.updateSettings({rationToastShown:true});},6500);}console.log('THIRSTY_READY '+JSON.stringify(result));});await collectors.start();}
app.whenReady().then(async()=>{
 if(!primary)return;if(mac)app.dock?.hide();
 widget=new BrowserWindow({...bounds(),transparent:true,frame:false,resizable:false,hasShadow:false,skipTaskbar:true,alwaysOnTop:true,focusable:false,acceptFirstMouse:true,show:false,backgroundColor:'#00000000',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:!testing,backgroundThrottling:true}});
 if(mac)widget.setVisibleOnAllWorkspaces(true,{visibleOnFullScreen:true});widget.loadFile(path.join(__dirname,'renderer/widget.html'));secure(widget);widget.once('ready-to-show',()=>widget.showInactive());widget.on('show',()=>emit('visibility',true));widget.on('hide',()=>emit('visibility',false));widget.on('closed',()=>{widget=null;});
 tray=new Tray(nativeImage.createFromPath(path.join(__dirname,mac?'renderer/img/trayTemplate.png':'renderer/img/tray.png')));tray.setToolTip('THIRSTY, AI sip counter');tray.on('double-click',openDashboard);buildMenu();
 api=await startAPI(()=>store,dataDir,{port:Number(process.env.THIRSTY_PORT)||47821,openDashboard,progress:()=>progress});console.log('THIRSTY_PORT '+api.port);
 screen.on('display-removed',()=>applySettings(true));screen.on('display-metrics-changed',()=>applySettings());
 await startCollectors();
 // Midnight changes streak/planet even when there are no new model calls.
 let lastDay=day();setInterval(()=>{if(store){if(day()!==lastDay){lastDay=day();store.checkBadges();store.save();}emit('stats',store.snapshot());}},60000).unref();
}).catch(e=>{console.error(e.stack);app.exit(1);});
app.on('window-all-closed',()=>{});
app.on('before-quit',event=>{if(quitting)return;event.preventDefault();quitting=true;(async()=>{await collectors?.stop();store?.save();await api?.close();tray?.destroy();app.quit();})().catch(()=>app.exit(1));});
// Test automation uses Electron's own API through Playwright, never an exposed HTTP control port.
module.exports={get widget(){return widget;},get dashboard(){return dashboard;},get store(){return store;},get collectors(){return collectors;},openDashboard};
