'use strict';
const $=id=>document.getElementById(id),sprites={chill:'sticker-10-thumbs-up',sipping:'thirsty-sip',sweating:'sticker-09-sweat-drop',bloated:'thirsty-burp',dramatic:'sticker-11-dead-x',sleeping:'sticker-07-sleep'};
const rules=['Take your first sip.','7 days under ration.','500 sips in one day.','1,000 Code + Codex sips in a day.','10 L in one day.','10 L across all days.','100 L across all days.','A full day under half your ration.','A sip between 02:00 and 05:00.','3 days under ration.','30 days under ration.','Poke Thirsty 50 times.'];
let stats,notifyTimer,formReady=false;
function notify(text){$('notification').textContent=text;$('notification').classList.add('show');clearTimeout(notifyTimer);notifyTimer=setTimeout(()=>$('notification').classList.remove('show'),4000);}
function render(s){if(!s || s.loading)return;stats=s;$('play').hidden=!/^https?:\/\//.test(s.settings?.siteUrl||'');$('litres').innerHTML=s.today.litres.toFixed(2)+' <span>L</span>';for(const k of ['sips','prompts','tokens'])$(k).textContent=s.today[k].toLocaleString();$('mood-label').textContent=s.mood.toUpperCase();$('today-pet').src='img/'+sprites[s.mood]+'.webp';$('ration-title').textContent=s.settings.usualDay?'YOUR USUAL DAY: '+s.settings.usualDay.toFixed(1)+' L':'DAILY RATION';$('ration-text').textContent=s.today.litres.toFixed(2)+' / '+s.ration+' L';$('ration-fill').style.width=Math.min(100,s.today.litres/s.ration*100)+'%';$('ration-fill').style.background=s.today.litres>s.ration?'var(--soda)':'var(--water)';$('streak').textContent=s.streak;$('planet-stage').textContent=s.planet.toUpperCase();$('planet').src='img/planet-'+s.planet+'.webp';$('source-total').textContent=s.today.sips+' SIPS';const max=Math.max(1,...Object.values(s.bySource).map(v=>v.sips));$('sources').replaceChildren();for(const [key,v]of Object.entries(s.bySource)){const d=document.createElement('div');d.className='source'+(v.sips?'':' zero');const name=document.createElement('div');name.className='name';const label=document.createElement('span');label.textContent=v.label;const count=document.createElement('b');count.textContent=v.sips;name.append(label,count);const track=document.createElement('div');track.className='track';const fill=document.createElement('div');fill.className='fill';fill.style.cssText=`width:${v.sips/max*100}%;background:${v.color}`;track.append(fill);d.append(name,track);$('sources').append(d);}
 const scale=Math.max(s.ration*1.2,...s.series.map(v=>v.litres*1.15)),chart=$('chart');chart.replaceChildren();for(const v of s.series){const bar=document.createElement('div');bar.className='bar'+(v.litres>s.ration?' over':'');bar.style.height=Math.max(3,v.litres/scale*108)+'px';bar.title=v.day+': '+v.litres.toFixed(3)+' L, '+v.sips+' sips';const label=document.createElement('span');label.textContent=Number(v.day.slice(-2));bar.append(label);chart.append(bar);}const line=document.createElement('div');line.className='line';line.style.bottom=22+s.ration/scale*108+'px';const label=document.createElement('span');label.className='line-label';label.style.bottom=line.style.bottom;label.textContent=s.ration+' L';chart.append(line,label);$('week-litres').textContent=s.series.slice(-7).reduce((n,d)=>n+d.litres,0).toFixed(2)+' L';
 const age=Date.now()-s.extensionLastSeen;$('extension-status').textContent=s.extensionLastSeen&&age<300000?'EXTENSION: CONNECTED, LAST SEEN '+Math.max(0,Math.floor(age/60000))+' MIN AGO':'EXTENSION: NOT INSTALLED';
 $('badge-grid').replaceChildren();for(const b of s.badges){const d=document.createElement('article');d.className='badge'+(b.unlocked?'':' locked');d.title=rules[b.id-1];const img=new Image();img.src='img/badge-'+String(b.id).padStart(2,'0')+'.webp';img.alt=b.name;img.width=80;img.height=80;const h=document.createElement('h2');h.textContent=b.name;const p=document.createElement('p');p.textContent=rules[b.id-1];d.append(img,h,p);if(b.unlocked){const check=document.createElement('span');check.className='badge-check';check.textContent='✓';d.append(check);}$('badge-grid').append(d);}$('badge-summary').textContent=s.badges.filter(b=>b.unlocked).length+' / 12 unlocked. Little wins add up.';
 if(!formReady){const f=$('settings-form');for(const key of ['ration','size','sound','ghost','startAtLogin','siteUrl','claudeDir','codexDir']){const input=f.elements.namedItem(key);if(input.type==='checkbox')input.checked=!!s.settings[key];else input.value=s.settings[key]??'';}for(const [key,v]of Object.entries(s.bySource)){const l=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='source:'+key;input.checked=s.settings.sources[key]!==false;l.append(input,document.createTextNode(v.label));$('source-settings').append(l);}formReady=true;}
}
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',()=>{for(const p of document.querySelectorAll('.page'))p.classList.toggle('active',p.id===b.dataset.tab);for(const n of document.querySelectorAll('[data-tab]'))n.classList.toggle('active',n===b);});
$('settings-form').addEventListener('submit',async event=>{event.preventDefault();const f=event.currentTarget,patch={sources:{}};for(const key of ['ration','size','siteUrl','claudeDir','codexDir']){const v=f.elements.namedItem(key).value;if(v)patch[key]=key==='ration'?Number(v):v;}for(const key of ['sound','ghost','startAtLogin'])patch[key]=f.elements.namedItem(key).checked;for(const key of Object.keys(stats.bySource))patch.sources[key]=f.elements.namedItem('source:'+key).checked;try{await window.thirsty.settings(patch);$('save-status').textContent='Saved. Tracking uses these settings now.';}catch(e){$('save-status').textContent=e.message;}});
$('play').addEventListener('click',()=>window.thirsty.play());$('csv').addEventListener('click',()=>window.thirsty.csv().then(file=>{if(file)notify('Daily CSV saved.');}));
function round(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();ctx.lineWidth=6;ctx.strokeStyle='#111111';ctx.stroke();}
async function share(){if(!stats)return;const canvas=$('share-canvas'),ctx=canvas.getContext('2d');await document.fonts.ready;ctx.fillStyle='#1463FF';ctx.fillRect(0,0,1200,675);ctx.fillStyle='#2EC4FF';ctx.beginPath();ctx.arc(1070,575,310,0,Math.PI*2);ctx.fill();round(ctx,58,55,1080,565,32,'#FFF3D6');ctx.fillStyle='#111111';ctx.font='65px Lilita';ctx.fillText('MY COOLING LOOP',105,142);ctx.font='130px Lilita';const week=stats.series.slice(-7);ctx.fillText(week.reduce((a,b)=>a+b.litres,0).toFixed(2)+' L',105,310);ctx.font='28px Fredoka';ctx.fillText('THIS WEEK, ONE LITTLE SIP AT A TIME',110,358);round(ctx,105,400,620,93,22,'#FFD12E');ctx.font='34px Lilita';ctx.fillText(week.reduce((a,b)=>a+b.sips,0).toLocaleString()+' SIPS',132,460);ctx.fillText(stats.streak+' DAY STREAK',380,460);const img=new Image();img.src='img/sticker-02-cheers.webp';await img.decode();ctx.drawImage(img,790,164,280,337);ctx.font='32px Lilita';ctx.fillText('@coolingloop',105,566);const file=await window.thirsty.share(canvas.toDataURL('image/png'));notify('Week card copied and saved.');return file;}
$('share').addEventListener('click',()=>share().catch(e=>notify(e.message)));window.thirsty.on('stats',render);window.thirsty.on('badge',b=>notify('UNLOCKED: '+b.name));document.fonts.ready.then(()=>window.thirsty.stats().then(render));window.thirstyDashboard={render,share};
